In [1]:
import pandas as pd

In [2]:
pd.read_csv('spaceX.csv')

,Unnamed: 0,flight_number,mission_name,mission_id,launch_year,launch_date_utc,rocket_id,rocket_name,rocket_type,payload_id,...,nationality,manufacturer,payload_type,payload_mass_lbs,orbit,fairings_reused,fairings_recovered,launch_site_id,launch_site_name,launch_success
0,0,1,FalconSat,[],2006,2006-03-24T22:30:00.000Z,falcon1,Falcon 1,Merlin A,FalconSAT-2,...,United States,SSTL,Satellite,43.000,LEO,False,False,kwajalein_atoll,Kwajalein Atoll,False
1,1,2,DemoSat,[],2007,2007-03-21T01:10:00.000Z,falcon1,Falcon 1,Merlin A,DemoSAT,...,United States,SpaceX,Satellite,NaN,LEO,False,False,kwajalein_atoll,Kwajalein Atoll,False
2,2,3,Trailblazer,[],2008,2008-08-03T03:34:00.000Z,falcon1,Falcon 1,Merlin C,Trailblazer,...,United States,Space Dev,Satellite,NaN,LEO,False,False,kwajalein_atoll,Kwajalein Atoll,False
3,3,3,Trailblazer,[],2008,2008-08-03T03:34:00.000Z,falcon1,Falcon 1,Merlin C,PRESat,...,United States,NaN,Satellite,NaN,LEO,False,False,kwajalein_atoll,Kwajalein Atoll,False
4,4,4,RatSat,[],2008,2008-09-28T23:15:00.000Z,falcon1,Falcon 1,Merlin C,RatSat,...,United States,SpaceX,Satellite,363.000,LEO,False,False,kwajalein_atoll,Kwajalein Atoll,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,131,107,Crew-1,['EE86F74'],2020,2020-11-16T00:27:00.000Z,falcon9,Falcon 9,FT,Crew-1,...,United States,SpaceX,Crew Dragon,NaN,ISS,NaN,NaN,ksc_lc_39a,KSC LC 39A,True
132,132,108,Sentinel-6 Michael Freilich,[],2020,2020-11-21T17:17:00.000Z,falcon9,Falcon 9,FT,Sentinel-6 Michael Freilich,...,United States,EUMETSAT,Satellite,3174.657,PO,NaN,NaN,vafb_slc_4e,VAFB SLC 4E,True
133,133,109,Starlink-15 (v1.0),[],2020,2020-10-24T15:31:00.000Z,falcon9,Falcon 9,FT,Starlink-15,...,United States,SpaceX,Satellite,33951.200,VLEO,False,NaN,ccafs_slc_40,CCAFS SLC 40,True
134,134,110,CRS-21,['EE86F74'],2020,2020-12-06T16:17:00.000Z,falcon9,Falcon 9,FT,CRS-21,...,United States,SpaceX,Dragon 2.0,NaN,ISS,NaN,NaN,ksc_lc_39a,KSC LC 39A,NaN
135,135,110,SXM-7,[],2020,2020-12-13T17:30:00.000Z,falcon9,Falcon 9,FT,SXM-7,...,United States,SSL,Satellite,NaN,GTO,NaN,NaN,ccafs_slc_40,CCAFS SLC 40,NaN